# Generated by Django 2.2.15 on 2020-08-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhibliMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=10)),
                ('producer', models.CharField(max_length=10)),
                ('release_date', models.DateTimeField()),
                ('rt_score', models.PositiveIntegerField()),
            ],
        ),
    ]
